### ISSUE TITLE
how to restrict namespaces?

### ISSUE THREAD

**Issue by supertiger1234** [vieroinc/viero-webrtc-sfu-client#1]
I'm a total noob to webrtc and i would like to know how i could restrict channels so only some users can enter. 
Another question: how can I let the server only create a new channel?

(i think "namespace" is the correct word to use and not "channels", idk xD)

**Comment by zgobolos** [comment]
Hi,

Assuming you want control on who is able to create channels you have 2 options:

1. Develop your own authenticated/authorized request/response flow and call https://github.com/vieroinc/viero-webrtc-signaling-server/blob/1ae6da166c9b879fce1d43df9281283deecedb35/src/index.js#L56 on the backend. You can use any http server you want or you can use our own VieroHTTPServer. If you use another, make sure the ports won't clash.
2. Develop your own authentication/authorization filter for VieroHTTPServer. A simple example on how: https://github.com/vieroinc/viero-common-nodejs/blob/master/src/http/filter/action.js. You can then load your filter as: https://github.com/vieroinc/viero-webrtc-sfu-example/blob/d324811cd2d12161f137cc4464e74c328f2eb430/server/index.js#L64.

**Comment by SupertigerDev** [comment]
Thanks a lot, while i'm still confused, I will still look at this.

**Comment by zgobolos** [comment]
The @viero/* npm packages are pretty new and I didn't have time to document them yet. I will in the coming days because I have to. Not to mention they are pretty much in the works. Once I document VieroHTTPServer and the VieroSignalingServer you will understand it better. The point with this SFU thingy is to provide a very thin layer on top of WebRTC for folks who don't want to use mammoths where a mice is enough.

**Comment by SupertigerDev** [comment]
Nice 😄 I'm currently making a chat application and want to add the calling functionality, hopefully i can understand this and add it someday
